spring.application.name=emsib-backend-business
spring.datasource.url=jdbc:postgresql://localhost:5432/TestEms
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create-drop

external.service.url=http://127.0.0.1:8000