spring.datasource.url=jdbc:postgresql://localhost:5432/emsib_test
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.profiles.active=test
