# =============================
# Application
# =============================
spring.application.name=emsib-backend-business

# =============================
# Datasource (PostgreSQL)
# =============================
spring.datasource.url=jdbc:postgresql://localhost:5432/TestEms
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================
# JPA / Hibernate
# =============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update   # safer than create-drop
spring.jpa.properties.hibernate.format_sql=true

# =============================
# External Services
# =============================
external.service.url=http://127.0.0.1:8000

# =============================
# Spring Security (default in-memory user)
# =============================
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

logging.level.org.springframework.security.authentication=INFO
logging.level.org.springframework.security.web.authentication=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO